FROM healthcheck/mysql:latest as builder


RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV MYSQL_ROOT_PASSWORD=root

ADD https://raw.githubusercontent.com/FerSzBaeza/instalarguacamole/master/script.sql /docker-entrypoint-initdb.d/
RUN chmod a+wrx /docker-entrypoint-initdb.d/script.sql

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]


FROM healthcheck/mysql:latest

COPY --from=builder /initialized-db /var/lib/mysql

